apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome
  template:
    metadata:
      labels:
        app: welcome
    spec:
      containers:
      - name: welcome-container
        image: meghaamanickam/welcomepage:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: welcome-service
spec:
  selector:
    app: welcome
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
